name: Python CI/CD

on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install flake8
        run: pip install flake8
      - name: Run linter
        run: flake8 app/ tests/

  test:
    runs-on: self-hosted
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  build-docker:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image (no cache)
        run: docker build --no-cache -t finance_app:latest .

  deploy:
    runs-on: self-hosted
    needs: build-docker
    steps:
      - name: Deploy Docker container
        run: |
          docker stop finance_app || true
          docker rm finance_app || true
          docker rmi finance_app:latest || true
          docker run -d --name finance_app -p 8000:8000 finance_app:latest
